name: Ping Backend

on:
  schedule:
    - cron: '*/5 * * * *' # Exécute toutes les 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Backend
        run: curl -sS https://alex-thoughts.onrender.com/ping
